- name: Deploy PFE projects smart-wallet-front to env "{{ ENV }}"

  hosts:
    "{{ 'smart-wallet-develop' if ENV|lower == 'develop' \
     else 'smart-wallet-testing' if ENV|lower == 'testing' \
     else 'smart-wallet-preprod' if ENV|lower == 'preprod' \
     else 'smart-wallet-production' if ENV |lower == 'prod' }}"

  vars:
    app_name: smart-wallet-app
    final_dest: /usr/share/nginx/{{ app_name }}/

  tasks:
    - name: Remove old files
      shell: "rm -rf {{ final_dest }}*"
      args:
        warn: false
      ignore_errors: yes

    - name: Deploy package to "{{ ENV }}"
      copy:
        src: "{{ item }}"
        dest: "{{ final_dest }}"
        owner: jenkins
        group: jenkins
        mode: 0644
      with_items:
        - "{{ app_name }}.tar.gz"

    - name: Extract archive
      unarchive:
        src: "{{ app_name }}.tar.gz"
        dest: '{{ final_dest }}'

    - name: remove extracted archive
      file:
        path: "{{final_dest }}{{ item }}"
        state: absent
      with_items:
        - "{{ app_name }}.tar.gz"
