- name: Deploy prosper-apps web wallet to env "{{ ENV }}"

  hosts:
    "{{ 'PA-web-wallet-develop' if ENV|lower == 'develop' \
     else 'PA-web-wallet-testing' if ENV|lower == 'testing' \
     else 'PA-web-wallet-preprod' if ENV|lower == 'preprod' \
     else 'PA-web-wallet-production' if ENV |lower == 'prod' }}"

  vars:
    app_name: web-wallet
    final_dest: /usr/share/nginx/{{ app_name }}/

  tasks:
    - name: Remove old files
      shell: "rm -rf {{ final_dest }}*"
      args:
        warn: false
      ignore_errors: yes

    - name: Deploy package to "{{ ENV }}"
      copy:
        src: "{{ item }}"
        dest: "{{ final_dest }}"
        owner: jenkins
        group: jenkins
        mode: 0644
      with_items:
        - PA-web-wallet.tar.gz

    - name: Extract archive
      unarchive:
        src: PA-web-wallet.tar.gz
        dest: '{{ final_dest }}'

    - name: remove extracted archive
      file:
        path: "{{final_dest }}{{ item }}"
        state: absent
      with_items:
        - PA-web-wallet.tar.gz
