- name: Deploy smart-wallet-front to env "{{ ENV }}"

  hosts:
    "{{ 'smart-wallet-front-develop' if ENV|lower == 'develop' \
     else 'smart-wallet-front-testing' if ENV|lower == 'testing' \
     else 'smart-wallet-front-preprod' if ENV|lower == 'preprod' \
     else 'smart-wallet-front-production' if ENV |lower == 'prod' }}"

  vars:
    app_name: smart-wallet-front
    final_dest: /opt/{{ app_name }}/

  tasks:
    - name: Deploy package to "{{ ENV }}"
      copy:
        src: "{{ item }}"
        dest: "{{ final_dest }}"
        owner: jenkins
        group: jenkins
        mode: 0740
      with_items:
        - smart-wallet-front

    - name: Updating Supervisord
      supervisorctl:
        name: "{{ app_name }}"
        state: restarted
