projectGroup: pfe
projectName: smart-wallet-front
 
### Slack
channel: git_pfe
 
### Test
runTests: true
testCommandFlag: "" #Test command
#testFolderPath: #the folder that contains test files

### Build
buildCommand:
    - "yarn install --no-progress"
    - "yarn run build 1> errorlint.log"
    - "tar -czvf smart-wallet.tar.gz -C dist ."

buildOutputFolder: ""
outputFilePattern: "smart-wallet.tar.gz"
 
### Deploy
deployUponTestSuccess: true

### Upload
uploadArtifacts: true
 
### Sonarqube analysis
sonarqubeTest: true
sonarProjectKey: smart-wallet-frontend
sonarSources: .
